# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yoshi theme
description: > # this means to ignore newlines until "baseurl:"
  A theme named after my cat. He still doesn't actually look like
  this.
baseurl: "/yoshi-theme" # the subpath of your site, e.g. /blog
url: "http://ryuslash.github.io" # the base hostname & protocol for your site
github_username:  ryuslash

# Build settings
markdown: kramdown
